["Fitted blazer with notch lapels and single button closure. Front welt pockets, decorative buttons on cuffs and back slit. Lined. The female model in the photo is 5'10 and wears a size 38.",
"Oversize double breasted blazer. Model with fine peak lapels, one top pocket and front pockets with flaps. Lined.", "Oversize blazer with notch lapels, button closure and decorative top pocket. Straight single-breasted model with front pockets trimmed with flaps. Lined. Female model pictured is 5'9 and is wearing a size XL.",
"Double-breasted blazer with notch lapels, one top bias pocket and front flap welt pockets. Straight cut model with decorative buttons on cuffs and back opening. Lined.", "Relaxed cut blazer with three-quarter sleeves. Straight cut with notch lapels and front pockets with flaps. Without zipper. Lined.",
"Relaxed cut blazer with three-quarter sleeves. Straight cut with notch lapels and front pockets with flaps. Without zipper. Lined.",
"Fitted blazer made of fabric with single button closure. Model with inset front pockets, covered button on cuffs and opening at the back. Lined.",
"Single breasted blazer in stretch fabric with notch lapels with decorative buttonhole and two front buttons, one top pocket, front pockets with flaps and one inside pocket. Decorative buttons on cuffs and back slit. Lined. Slim fit - slim fit through the chest and waist, with slightly narrower sleeves for a slim silhouette. The male model in the photo is 6'2 and wears a size 44."
"Single breasted blazer in linen with notch lapels with decorative buttonhole. Model with two front buttons, one top pocket, front pockets with flap, two inside pockets, decorative buttons on cuffs and back opening. Lined. Slim fit - fitted at chest and waist, with slightly narrower sleeves for a refined silhouette. Slim fit.",
"Double-breasted linen blazer with peak lapels and decorative buttonhole. Standard cut model with top pocket, front pockets with flap and two inside pockets. Decorative buttons on cuffs and double vent at back.",
"Synthetic leather boots with ankle shaft, laces in front and belt loop at the back. Synthetic leather insole and thick sole. Heel 3 cm.",
"Studio Collection. Vegea vegetable leather clogs with metal studs. Model with thick sole and partially covered square heel. Lining and padded insole in vegetable Vegea leather.",
"Slightly padded slippers in quilted synthetic leather. Wide strap with hook-and-loop fastener and padded synthetic leather insole. Ribbed sole.",
"Synthetic leather moccasins with decorative bow in front. Satin lining and synthetic leather insole. Thick sole with design. Heel 6 cm.",
"Synthetic suede high top sneakers with mesh, knit and synthetic leather sections. Padded collar, laces with hooks on the upper and loop at the back. Lining and insole in piqué. Thick sole with design. Sole thickness 5 cm.",
"Synthetic leather moccasins with stitching and decorative bow in front. Satin lining and synthetic leather insole. Thick sole with design. Heel 4 cm.",
"Synthetic leather boots with ankle shaft, laces in front and belt loop at the back. Synthetic leather insole and thick sole. Heel 3 cm.",
"Synthetic leather Chelsea boots with half shaft, elastic sides and front and back straps. Satin lining and synthetic leather insole. Thick sole with ribbed design.",
"Synthetic leather sandals with frontal straps and bracelet with hook-and-loop fastener. Synthetic leather insole and thick sole with ribbed design. Thickness of the sole 6 cm.",
"Synthetic leather mules with square toe, asymmetrical instep strap and covered square heel. Synthetic leather lining and insole. Heel 10 cm.",
"Recycled polyester bikini bottoms with ruffle trim. Low-waisted model with semi-covered back. Fully lined.",
"Ribbed swimsuit with adjustable straps and removable padded cups that shape and provide good support. Semi-covered back. Lined.",
"Extra tight-fitting swimsuit with shaping effect at the waist. Model with V-neckline, adjustable straps and removable padded cups that shape the bust and provide good support. Decorative knot in front and semi-covered back. Fully lined.",
"Triangle bikini top in recycled polyester with overcast ruffle trim. Adjustable thin straps with multi-function back closure and removable padded cups that shape the bust and provide good support. Metal back closure. Lined. No underwire.",
"Studio Collection. Triangle bikini top with leopard print. Model with spaghetti straps and thin strap at the bottom, both elastic and adjustable. Gold metal clasp at the back.",
"Printed knee-length swim trunks with coated elastic and drawstring waist, side pockets and insert pocket with hook-and-loop closure at the back. Soft mesh inner briefs.",
"Fabric swimsuit with elastic waistband and drawstring, bias pockets and a back pocket with hook-and-loop closure. Mesh inner briefs.",
"Fabric swimsuit with elastic waistband and drawstring, bias pockets and a back pocket with hook-and-loop closure. Mesh inner briefs.",
"Printed knee-length swim trunks with coated elastic and drawstring waist, side pockets and insert pocket with hook-and-loop closure at the back. Soft mesh inner briefs.",
"Recycled polyamide swimsuit with elastic waistband and drawstring, bias pockets and a back pocket with hook-and-loop closure. Mesh inner briefs.",
"Five-pocket jeans in stretch cotton denim. Standard waist model with fitted legs and zipper and button closure.",
"Five-pocket jeans in stretch cotton denim. Standard waist model with extra-fitted legs and zipper closure with button.",
"Five-pocket jeans in thick cotton denim. Standard waist, zipper closure with button and wide leg for a loose fit.",
"Five-pocket jeans in stretch cotton denim. Standard waist model with fitted legs and zipper and button closure.",
"Five-pocket denim jeans with standard waistband, zipper and button closure and slim leg. Made with Lycra Freefit technology that provides optimum stretch, maximum mobility and excellent comfort.",
"Five-pocket jeans in washed cotton denim. High-waisted model with wide straight legs and zipper closure with button.",
"Five-pocket jeans in stretch cotton denim. Low-waisted model with zipper closure with button and wide legs with flared hem.",
"Five-pocket jeans in stretch cotton denim. Low-waisted model with zipper and button closure, back pockets with flap and button, and flared hems.",
"Five-pocket jeans in washed cotton denim. High-waisted model with wide straight legs and zipper closure with button.",
"Five-pocket ankle jeans in washed stretch denim. High-waisted model with zipper closure with button and fitted legs.",
"Cotton twill bucket hat with small motif on the front and embroidered eyelets on the sides. Anti-sweat band and cotton lining.",
"Cotton twill cap with adjustable metal clasp at the back. Cotton sweatband.",
"Bucket hat with text motif. Elastic drawstring for optimal fit. Cotton sweatband and mesh lining.",
"Cotton twill cap with adjustable metal clasp at the back. Cotton sweatband.",
"Cotton twill and mesh cap with embroidered appliqué on front and adjustable plastic closure on back. Cotton sweatband.",
"Regenerated leather belt with metal buckle. Width 3.5 cm.",
"Regenerated dark blue leather belt with metal buckle. Width 3.5 cm.",
"Brown leather belt with metal buckle. Width 3.3 cm.",
"Braided elastic belt with synthetic leather details and metal buckle. Width approx. 3.5 cm.",
"Black leather belt with metal buckle. Width 3.3 cm.",
"Mini shoulder bag with small fabric appliqué on the front, top zipper with double slider and removable adjustable strap with buckles and plastic snap hook. One exterior zippered compartment and one interior compartment. Lined. Width 4 cm. Length 15.5 cm. Height 20.5 cm.",
"Small weekend bag with two handles, top zipper and removable adjustable shoulder strap. One exterior and one interior zippered compartment. Metal buckles on the sides to adjust the size. Lined. Width 22 cm. Length 48 cm. Height 31 cm.","Fabric backpack with adjustable padded handle and straps. Top zipper, one exterior zippered compartment and two interior compartments, one for laptop and one smaller zippered compartment. Padded back. Lined. Width 13 cm. Length 30 cm. Height 43 cm.","This shopper bag is made of partially recycled cotton canvas. Model with double handle in contrasting color that continues downwards, an inner compartment with zipper and base in contrasting color. Width 35 cm. Height 47 cm. Length 55 cm. Pocket measures 20x21 cm.","Multifunctional canvas bag that can be used as a backpack and as a weekend bag. Two top handles and zipper closure. Lightly padded adjustable straps with snap closure and side mesh concealment pocket. Exterior zippered compartment and interior zippered pocket on flap. Width approx. 30 cm. Height approx. 30 cm. Length approx. 52 cm.",
"Fabric shoulder bag with zippered top and removable adjustable shoulder strap with buckle and metal carabiners. One exterior compartment with hidden zipper and one interior mesh compartment. Lined. Width 7 cm. Height 16 cm. Length 23 cm.,"
"Fabric fanny pack with large zippered front compartment, zippered back compartment and open inner compartment. Adjustable strap with plastic snap closure. Lined. Width approx. 6 cm. Height approx. 15 cm. Length approx. 18 cm.",
"Bum bag with one large zippered compartment in front, one zippered compartment in back and one inner compartment. Adjustable strap with plastic snap closure. Lined. Measures 5x18x32 cm.",
"Weekend bag in synthetic leather with two handles, removable shoulder strap, zipper on top and two compartments inside. Support studs on the base. Lined. Measures approx. 22x31x48 cm.",
"Multifunctional ripstop bag that can be used as a backpack or tote bag. Double handle model with zippered closure, lightly padded adjustable straps with snap closure and back compartment for strap storage. Zippered front compartment, open mesh side compartments and interior zippered pocket for easy folding and storage. Practical strap to carry it folded. Lined. Width approx. 8 cm. Length approx. 34 cm. Height approx. 35 cm.",
"Metal earrings and ear cuffs. Six hoop earrings. Seven ear cuffs. Made with recycled zinc.",
"Gold plated metal chain anklets in different designs. Adjustable length and spring ring closure.",
"Round sunglasses with plastic frame, lenses and temples. Polarized tinted lenses with UV protection for color clarity and contrast while eliminating glare. Supplied in a fabric case with drawstring.",
"Sunglasses with plastic frame. Plastic tinted lenses with UV protection."]